/*
 * Main configuration file
 */

#ifndef H_CONFIGURATION
#define H_CONFIGURATION

#define KAOS_VERSION_MAJOR 0
#define KAOS_VERSION_MINOR 3
#define KAOS_VERSION_REVISION 0

#define KAOS_SCREEN_WIDTH 1440
#define KAOS_SCREEN_HEIGHT 900
#define KAOS_FONTS_WIDTH 8
#define KAOS_FONTS_HEIGHT 16
#define KAOS_FONTS_SIZE KAOS_FONTS_WIDTH*KAOS_FONTS_HEIGHT*255

#endif /* H_CONFIGURATION */
