/*
 * Main configuration file
 */

#ifndef H_CONFIGURATION
#define H_CONFIGURATION

#define KAOS_VERSION_MAJOR 0
#define KAOS_VERSION_MINOR 2
#define KAOS_VERSION_REVISION 2

#define KAOS_SCREEN_WIDTH 1024
#define KAOS_SCREEN_HEIGHT 768
#define KAOS_FONTS_SIZE 8*16*255

#endif /* H_CONFIGURATION */
